pull_request_rules:

- name: auto-merge
  description: automatic merge for main with >= 2 approved reviews, all requested reviews have given feedback, not held, and CI is successful
  conditions:
    - "#approved-reviews-by>=2"
    - "#review-requested=0"
    - "#changes-requested-reviews-by=0"
    - or:
      - base=main
      - base~=release-.*
    - label!=hold
    - label!=do-not-merge
    - label!=needs-rebase
    - check-success=DCO

    # If files are changed in .github/, the actionlint check must pass
    - or:
      - and:
        # regex should match the one in .github/workflows/actionlint.yml
        - files~=.github/workflows/.*\.ya?ml$
        - check-success=actionlint
      - -files~=.github/workflows/.*\.ya?ml$

    # e2e workflow
    - or:
      - and:
        - check-success=e2e
        - or:
          - files~='.*\.py$'
          - files~=pyproject.toml$
          - files~=requirements.*\.txt$
          - files~=.github/workflows/e2e.yml$
      - and:
        - -files~='.*\.py$'
        - -files~=pyproject.toml$
        - -files~=requirements.*\.txt$
        - -files~=.github/workflows/e2e.yml$

    # lint and test must pass if files change that would trigger this job
    - or:
      - and:
        - check-success=lint
        - check-success=test-workflow-complete
        - or:
          # see .github/workflows/lint.yml and test.yml
          - files~=.*\.py$
          - files~=pyproject.toml$
          - files~=requirements.*\.txt$
          - files~=tox.ini$
          - files~=scripts/[^/]+\.sh$
          - files~=.github/.*$
      - and:
        - -files~=.*\.py$
        - -files~=pyproject.toml$
        - -files~=requirements.*\.txt$
        - -files~=tox.ini$
        - -files~=scripts/[^/]+\.sh$
        - -files~=.github/.*$

    - or:
      - and:
        - or:
          - files~='.*\.md'
          - files='.markdownlint-cli2.yaml'
          - files='.github/workflows/docs.yml'
        - check-success=markdown-lint
      - and:
        - -files~='.*\.md'
        - -files='.markdownlint-cli2.yaml'
        - -files='.github/workflows/docs.yml'

  actions:
    merge:
      method: merge
    delete_head_branch:

- name: label-cicd
  description: Automatically apply CI/CD label
  conditions:
    - or:
      - files=.github/mergify.yml
      - files=.github/workflows/**/*
      - files=.pylintrc
      - files=.spellcheck-en-custom.txt
      - files=.spellcheck.yml
      - files=tox.ini
      - files=.markdownlint-cli2.yaml
  actions:
    label:
      add:
        - CI/CD

- name: label-documentation
  description: Automatically apply documentation label
  conditions:
    - or:
      - files~=.*\.md
      - files~=docs/.*
  actions:
    label:
      add:
        - documentation

- name: label-testing
  description: Automatically apply testing label
  conditions:
    - or:
      - files~=tests/.*
      - files=tox.ini
  actions:
    label:
      add:
        - testing

- name: ping author on conflicts and add 'needs-rebase' label
  conditions:
      - conflict
      - -closed
  actions:
    label:
      add:
        - needs-rebase
    comment:
      message: |
       This pull request has merge conflicts that must be resolved before it can be
       merged. @{{author}} please rebase it. https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

- name: remove 'needs-rebase' label when conflict is resolved
  conditions:
      - -conflict
      - -closed
  actions:
    label:
      remove:
        - needs-rebase

- name: Apply ci-failure label if any CI checks have failed
  conditions:
      - "#check-failure>0"
  actions:
    label:
      add:
        - ci-failure

- name: Remove ci-failure label if no failures are present
  conditions:
      - "#check-failure=0"
  actions:
    label:
      remove:
        - ci-failure
