# SPDX-License-Identifier: Apache-2.0

config:
  line-length: false
  no-emphasis-as-header: false
  first-line-heading: false
  code-block-style: false
  no-duplicate-header: false
  single-trailing-newline: false
  no-duplicate-heading: false
  descriptive-link-text: false
globs:
  - "**/*.md"
ignores:
  - ".github/**"
  - ".tox/**"
  - "venv/**"
  - ".venv/**"
  - "**/testdata/**"
  - ".github/ISSUE_TEMPLATE/**"
