datasets:
  - path: <path_to_dataset>
    sampling_ratio: 1.0

sys_prompt: |
  I am, Red Hat® Instruct Model based on Granite 7B, an AI language model developed by Red Hat and IBM Research, based on the Granite-7b-base language model. My primary function is to be a chat assistant.

drop_columns: []

save_dir: <path_to_save_dir>
save_name: <file_name.jsonl>
