# SPDX-License-Identifier: Apache-2.0

name: Spellcheck

on:
  push:
    branches:
      - "main"
    paths:
      - '**.md'
      - '.github/workflows/spellcheck.yml' # This workflow
  pull_request:
    branches:
      - "main"
    paths:
      - '**.md'
      - '.github/workflows/spellcheck.yml' # This workflow

env:
  LC_ALL: en_US.UTF-8

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  spellcheck:
    name: Spellcheck (en_US)
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@584b2ae95998967a53af7fbfb7f5b15352c38748 # v0.49.0
