# SPDX-License-Identifier: Apache-2.0

name: Spellcheck

on:
  push:
    branches:
      - "main"
    paths:
      - '**.md'
      - '.github/workflows/spellcheck.yml' # This workflow
  pull_request:
    branches:
      - "main"
    paths:
      - '**.md'
      - '.github/workflows/spellcheck.yml' # This workflow

env:
  LC_ALL: en_US.UTF-8

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  spellcheck:
    name: Spellcheck (en_US)
    runs-on: ubuntu-latest
    steps:
      - name: "Harden Runner"
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
         egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: "Checkout"
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          fetch-depth: 0

      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@5922d6e80234a4b230c51f2af3b9e29f29263eb7 # v0.39.0
